name: 'Changelog'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - changelog.js

jobs:
  build:
    name: 'Changelog'
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: 'pnpm'

      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile

      - name: Generate changelog
        run: node ./changelog.js

      - name: Checkout gh-pages
        id: checkout
        run: |
          git add changelog/depiction.json changelog/data.json
          git stash
          git checkout gh-pages

          # Prevent conflicts by overwriting the files with the ones in the stash
          git checkout stash -- changelog/depiction.json changelog/data.json

          changes=$(git status --porcelain changelog/depiction.json changelog/data.json | wc -l)
          echo "::set-output name=changes::$changes"

      - name: Commit and push changes
        if: ${{ steps.checkout.outputs.changes != 0 }}
        run: |
          git config --global user.name 'zbrabot'
          git config --global user.email 'zbrabot@users.noreply.github.com'

          # Make sure only the changelog/depiction.json and changelog/data.json files get committed
          git reset
          git add changelog/depiction.json changelog/data.json
          git commit --message "chore(changelog): automated update at $(date '+%F %T')"

          git push
