name: 'Update news'

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: 'Update news'
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Checkout main
        run: git checkout main

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Shrink news
        id: news
        run: |
          node ./index.js
          changes=$(git status --porcelain docs/reddit-news.json | wc -l)
          echo "::set-output name=changes::$changes"

      - name: Commit push changes
        if: ${{ steps.news.outputs.changes != 0 }}
        run: |
          git config --global user.name 'zbrabot'
          git config --global user.email 'zbrabot@users.noreply.github.com'

          git add docs/reddit-news.json
          git commit --message "chore: automated update at $(date '+%F %T')"

          git push
